[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.5.1"
gcd = "2.3.0"
itertools = "0.13.0"
rand = "0.8.5"
regex = "1.11.1"
strum = "0.26.3"
strum_macros = "0.26.4"

[[bench]]
name = "day01"
harness = false
